--- #YAML:1.0
module_name: Acme-Convert-ASCII-String
dist_version_from: lib/Acme/Convert/ASCII/String.pm
installdirs: site
requires:
    Exporter: 0 
distribution_type: module
license: perl
dist_abstract: Convert character strings to ASCII
